//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity2ExtendingUsersAndRoles.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tableItem
    {
        public int ItemId { get; set; }
        [Required(ErrorMessage = "Employee Name is required")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Enter charatcter only")]
        [Display(Name = "")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage = "Pleae select your Gender")]
        [Display(Name = "")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Employee Department is required")]
        [Display(Name = "")]
        public string Department { get; set; }
        [Required(ErrorMessage = "Employee Position is required")]
        [Display(Name = "")]

        public string Position { get; set; }
        [Required(ErrorMessage = "Employee Email is required")]
        [RegularExpression("[a-z0-9][-a-z0-9._]+@([-a-z0-9]+.)+[a-z]{2,5}$", ErrorMessage = "Enter a valid email address")]
        [Display(Name = "")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Employee MobileNumber is required")]
        [Display(Name = "")]
        public string MobileNumber { get; set; }
        [Required(ErrorMessage = "Employee Office is required")]
        [Display(Name = "")]
        public string OfficeNumber { get; set; }
        [Required(ErrorMessage = "Pleae select your Region")]
        [Display(Name = "")]
        public string Region { get; set; }
        [Required(ErrorMessage = "Pleae select your Subcity")]
        [Display(Name = "")]
        public string SubCity { get; set; }
        [Required(ErrorMessage = "Pleae select your Woreda")]
        [Display(Name = "")]
        public string Woreda { get; set; }
        [Required(ErrorMessage = "Employee HouseNumber is required")]
        [Display(Name = "")]
        public string HouseNumber { get; set; }
        [Required(ErrorMessage = "Pleae select your MaterialType")]
        [Display(Name = "")]
        public string MaterialType { get; set; }
        [Required(ErrorMessage = "Number of Material is required")]
        [Display(Name = "")]
        public string NumberOfMaterial { get; set; }
        [Required(ErrorMessage = "Serial Number is required")]
        [Display(Name = "")]
        public string SerialNumber { get; set; }
        [Display(Name = "")]
        public System.DateTime DateTaken { get; set; }
        [Required(ErrorMessage = "Pleae select your Status")]
        [Display(Name = "")]
        public string Status { get; set; }
        [Display(Name = "")]
        public string Description { get; set; }
    }
}
